export const productsData = [
  {
    id: 1,
    name: "Megan Rapinoe",
    price: 23,
    offPrice: 23,
    discount: 0,
    imageURL: "https://s2.uupload.ir/files/shop_01_l4md.jpg",
  },
  {
    id: 2,
    name: "KNIT VEST",
    price: 95,
    offPrice: 85,
    discount: 10,
    imageURL: "https://s2.uupload.ir/files/shop_02_m1h5.jpg",
  },
  {
    id: 3,
    name: "RIB TANK TOP",
    price: 77,
    offPrice: 70,
    discount: 7,
    imageURL: "https://s2.uupload.ir/files/shop_03_a1nk.jpg",
  },
  {
    id: 4,
    name: "Pants Men",
    price: 130,
    offPrice: 100,
    discount: 30,
    imageURL: "https://s2.uupload.ir/files/shop_04_pym1.jpg",
  },
  {
    id: 5,
    name: "Coats Men",
    price: 250,
    offPrice: 250,
    discount: 0,
    imageURL: "https://s2.uupload.ir/files/shop_05_ws70.jpg",
  },
  {
    id: 6,
    name: "Black Scarf",
    price: 287,
    offPrice: 250,
    discount: 37,
    imageURL: "https://s2.uupload.ir/files/shop_06_qe.jpg",
  },
  {
    id: 7,
    name: "Blue Coats Men",
    price: 66,
    offPrice: 66,
    discount: 0,
    imageURL: "https://s2.uupload.ir/files/shop_07_m7gy.jpg",
  },
  {
    id: 8,
    name: "Watch Women",
    price: 80,
    offPrice: 65,
    discount: 15,
    imageURL: "https://s2.uupload.ir/files/shop_08_6ufb.jpg",
  },
  {
    id: 9,
    name: "Sun Glass",
    price: 54,
    offPrice: 54,
    discount: 0,
    imageURL: "https://s2.uupload.ir/files/shop_09_e6yh.jpg",
  },
];
